[package]
name = "hyper-socks"
version = "0.1.0"
authors = ["Steven Fackler <sfackler@palantir.com>"]

[dependencies]
socks = { version = "0.1", path = "../socks" }
hyper = { version = "0.7", default_features = false }

[dev-dependencies]
hyper = "0.7" # to pick up openssl stuff
